// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fikjovlkojjjudjjghno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpa2pvdmxrb2pqanVkampnaG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDI5ODEsImV4cCI6MjA3MjI3ODk4MX0.C60mWH9bFrrxBGn1Oe2H5s4tX2bdlfY5l2AgfawozYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});